<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\AnalystPlan;
use App\Models\Subscription;
use App\Models\AnalystAssignment;
use App\Models\TradeAccount;
use App\Models\Trade;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;
use App\Enums\AccountType;
use App\Enums\TradeDirection;
use App\Enums\TradeOutcome;
use App\Enums\MarketSession;

class PremiumAnalystFeedbackSeeder extends Seeder
{
    public function run()
    {
        // 1. Create Analyst User
        $analyst = User::firstOrCreate(
            ['email' => 'analyst_premium@example.com'],
            [
                'name' => 'Premium Analyst',
                'password' => Hash::make('password'),
                'role' => 'analyst',
                'email_verified_at' => now(),
            ]
        );

        // 2. Create Trader User
        $trader = User::firstOrCreate(
            ['email' => 'trader_premium@example.com'],
            [
                'name' => 'Premium Trader',
                'password' => Hash::make('password'),
                'role' => 'trader',
                'email_verified_at' => now(),
            ]
        );

        // 3. Create Premium Plan for Analyst
        $plan = AnalystPlan::firstOrCreate(
            [
                'analyst_id' => $analyst->id,
                'tier' => 'premium',
            ],
            [
                'price' => 50.00,
                'features' => ['Weekly Feedback', 'Trade Analysis', 'Priority Support'],
                'is_active' => true,
            ]
        );

        // 4. Create Active Subscription for Trader
        Subscription::firstOrCreate(
            [
                'trader_id' => $trader->id,
                'analyst_id' => $analyst->id,
            ],
            [
                'plan' => 'premium', 
                'price' => 50.00,
                'status' => 'active',
                'current_period_start' => Carbon::now(),
                'current_period_end' => Carbon::now()->addMonth(),
            ]
        );

        // 4.5. Create Analyst Assignment (required for authorization)
        AnalystAssignment::firstOrCreate([
            'analyst_id' => $analyst->id,
            'trader_id' => $trader->id,
            'assigned_by' => null, // Auto-assigned by seeder
        ]);

        // 5. Create Trade Account for Trader
        $account = TradeAccount::firstOrCreate(
            [
                'user_id' => $trader->id,
                'account_name' => 'Premium Testing Account',
            ],
            [
                'account_type' => AccountType::DEMO,
                'broker' => 'Test Broker',
                'initial_balance' => 10000,
                'currency' => 'USD',
                'is_system_default' => false,
            ]
        );

        // 6. Create Trades for Feedback
        $this->createTrades($account, $trader->id, 5, true);
        $this->createTrades($account, $trader->id, 5, false);

        $this->command->info('Premium Analyst Feedback Seeder ran successfully.');
        $this->command->info('Analyst: analyst_premium@example.com / password');
        $this->command->info('Trader: trader_premium@example.com / password');
    }

    private function createTrades($account, $userId, $count, $isWin)
    {
        for ($i = 0; $i < $count; $i++) {
            Trade::create([
                'user_id' => $userId,
                'trade_account_id' => $account->id,
                'pair' => 'EURUSD',
                'direction' => $isWin ? TradeDirection::BUY : TradeDirection::SELL,
                'entry_date' => Carbon::now()->subDays(rand(1, 30)),
                'exit_date' => Carbon::now()->subDays(rand(1, 30))->addHours(2),
                'entry_price' => 1.1000,
                'exit_price' => $isWin ? 1.1050 : 1.0950,
                'lot_size' => 1.0,
                'stop_loss' => 1.0900,
                'take_profit' => 1.1100,
                'outcome' => $isWin ? TradeOutcome::WIN : TradeOutcome::LOSS,
                'profit_loss' => $isWin ? 500.00 : -500.00,
                'pips' => $isWin ? 50.0 : -50.0,
                'session' => MarketSession::LONDON,
                'notes' => 'Test trade generated by seeder for feedback purposes.',
                'has_feedback' => false,
                'trade_type' => 'Day Trading',
            ]);
        }
    }
}
